### ISSUE TITLE
New update suggestion by Long time reader - thanks! for https://itsfoss.com/to-do-list-apps-linux/

### ISSUE THREAD

**Issue by abhishekpc** [itsfoss/feedback#16]
Planner has been renamed to Planify.  (And I also tried the latest beta.)
Unfortunately neither one runs properly on Linux Mint 21.1 (Cinnamon).  You can create and name a project, but there is no way to add information, schedule, or complete the project.  
Your description sounds very useful; I just wish it would run on Mint.

**Comment by gojo-limitless** [comment]
Updated, and updated meta SEO to 2024, will check for other update things in the article as a separate task.
