### ISSUE TITLE
New update suggestion by WaffleOne for https://itsfoss.com/improve-privacy/

### ISSUE THREAD

**Issue by abhishekpc** [itsfoss/feedback#30]
Hello, I really reaaaallly appreciated your article on improving privacy. I see that for private message, you advised people to use signal, however I do feel like Session would have its place here ! I don't know what's your take on Session but it doesn't require a phone number to be able to use it so I do feel like this is the go to (as it has been for me). Besides Session, Silence is also a SSMS app that could be a more user-friendly alternative !

**Comment by gojo-limitless** [comment]
An alternative suggestion from the reader. Will mention it, Signal gives better usability with privacy, hence won't be replacing it with Session.
