### ISSUE TITLE
New update suggestion by Paul Mann for https://itsfoss.com/dg-ux-os/

### ISSUE THREAD

**Issue by abhishekpc** [itsfoss/feedback#31]
Message for Bill Dyer please ... I'm STILL supporting DG/UX for couple of UK-based companies!  It still LIVES!!!!!  Running 4.20MU06 on AV/3600 and AV/3700.

**Comment by gojo-limitless** [comment]
If the one contacted can share some website information/that there's an update to the OS, we can add this information. No clue otherwise.
