### ISSUE TITLE
New update suggestion by KC for https://itsfoss.com/note-taking-apps-linux/

### ISSUE THREAD

**Issue by abhishekpc** [itsfoss/feedback#35]
Have you looked at Logseq?

I have used and tested many of the apps you have listed. I have stuck with Logseq for over a year.

The key in my opinion is:
- Your notes are stored in basic text (with Markdown) files
- Local first
- Easy to sync (via Syncthing)

Thanks.

**Comment by gojo-limitless** [comment]
Added Logseq, and updated the metadata to reflect 2024.
