### ISSUE TITLE
New update suggestion by Ernst  for https://itsfoss.com/use-snap-packages-ubuntu-16-04/#

### ISSUE THREAD

**Issue by abhishekpc** [itsfoss/feedback#36]
Hello, 
you article: well done, good overview. 
And I like the attitude to let the reader suggest improvements and corrections. 

I want just to point out that I cannot access the pdf cheat sheet for snapd. 

Best Regards, 

Ernst

**Comment by gojo-limitless** [comment]
Updated with a link the cheatsheet file
