### ISSUE TITLE
New update suggestion by Woody for https://itsfoss.com/libreoffice-vs-freeoffice/

### ISSUE THREAD

**Issue by abhishekpc** [itsfoss/feedback#51]
You wrote: "Additionally, FreeOffice cuts back on features like Spell checking, synonym dictionaries, tabs, macros, and free technical support. You can only avail of these benefits with SoftMaker Office with a premium subscription."

In fact, FreeOffice has the same spell checking that's included in the paid version. FreeOffice does not include a thesaurus, but computer-based thesauri are useless anyway, so that's not a loss. And FreeOffice gets free tech support through SoftMaker's support forum. The support from that is far superior to the free support available for LibreOffice.

The only reason to choose LibreOffice over FreeOffice is if you need the Base database. Unfortunately, while Base is fairly easy to use for creating a database, the report function is Byzantine and unusable.

**Comment by gojo-limitless** [comment]
Updated
