### ISSUE TITLE
New update suggestion by Pat Decker for https://itsfoss.com/upgrade-ubuntu-version/?ref=foss-weekly-newsletter

### ISSUE THREAD

**Issue by abhishekpc** [itsfoss/feedback#59]
You said: 

upgrading to Ubuntu 24.04 Jammy Jellyfish from 23.10 or 22.04

Should be:

upgrading to Ubuntu 24.04 Noble Numbat from 23.10 or 22.04

**Comment by gojo-limitless** [comment]
Fixed
