### ISSUE TITLE
New update suggestion by Pat Decker for https://itsfoss.com/ollama-setup-linux/

### ISSUE THREAD

**Issue by abhishekpc** [itsfoss/feedback#61]
I see a few.

This:
you should see a whirring sound

Should probably be:
you should hear a whirring sound.

This:
Even if you do know Docker

Should probably be:
Even if you do not know Docker

This:
more than one LLMs at a time

Should probably be:
more than one LLM at a time

This:
With that aside, let's Ollama itself.

Should probably be:
With that aside, let's remove Ollama itself.

**Comment by gojo-limitless** [comment]
Fixed.
