### ISSUE TITLE
New update suggestion by Vlad for https://itsfoss.com/update-feedback/

### ISSUE THREAD

**Issue by abhishekpc** [itsfoss/feedback#77]
Hey this is just a suggestion. Your blog is so good , and you are a skilled guy. Why dont you mirror your content in hive blockchain, monetize it imortalize it and stuff. if you need any assistance doing that my hive name is xvlad, and my website is https://skatehive.app , cheers !

**Comment by gojo-limitless** [comment]
Doesn't need any attention, closing.
